version: '2'

services:
  ldt:
    container_name: ldt
    image: local/tomcat:9.0.0.M11
    hostname: ldt.local
    ports:
      - "8080:8080"
    volumes:
        - /c/Users/rpl01081/Documents/Kitematic/virtuoso/data:/usr/local/tomcat/webapps
        - /c/Users/rpl01081/Documents/Kitematic/share_virtuoso_tomcat:/usr/local/tomcat/temp:z
    networks:
      - ldt

  virtuoso:
    container_name: virtuoso_new
    image: tenforce/virtuoso
    hostname: virtuoso.local
    ports:
      - "1111:1111"
      - "8890:8890"
    environment:
      DBA_PASSWORD: "dba"
      SPARQL_UPDATE: "true"
      VIRTUOSO_DBA_PWD: dba
  #  volumes:
  #    - ./virtuoso_data:/var/lib/virtuoso/db:z
  #    - ./shared_import:/var/lib/virtuoso/usr/local/tomcat/temp:z
    networks:
      - ldt

networks:
  ldt:
    external:
      name: ldt
